# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb462785642f9ae732261d29fc3ca3855c3b9cb41e29f886c94c1848f424647be86d7a2b36dddc00a9949b5221e94483fe20a08f0ed01aa6220b5617c40ab59

test:
  secret_key_base: 697c781f811fb54a7ed4e17f17337e1ca158b7b9ef6f66294298e5d8c9326a68419fa6770dc8f084b0590980c76a05c2575f8e9bdb91ed36ebc797bc646b29a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
